theme: jekyll-theme-midnight
site_url: https://chriswestwood.github.io/Giants-BoardGame/
title: 'Giants - The Board Game (TTS Mod)'
repo_name: 'chriswestwood/Giants-BoardGame'
repo_url: 'https://github.com/chriswestwood/Giants-BoardGame'

